---
openwrt_install_recommended_packages: false

openwrt_config_network:
  globals:
    ula_prefix: "fd27:70fa:5c1d::/48"
  interfaces:
    test: { proto: static, ipaddr: 192.168.255.254, netmask: 255.255.255.0, gateway: 192.168.255.1, metric: 20, dns: [192.168.255.2] }
    test_dhcp: { ifname: eth10 }
